// BULLET_SCRIPT(
// 	.ID = "player_basic",
//     .Count = 5,
//     .Instr = {
//         [0] = { .OPCODE = OP_SPAWN, .arg1 = 10, .arg2 = 0, .arg3 = 0, .arg4 = 0 },
//         [1] = { .OPCODE = OP_SET_VEL, .arg1 = 200, .arg2 = 0, .arg3 = 0, .arg4 = 0 },
//         [2] = { .OPCODE = OP_WAIT, .arg1 = 60, .arg2 = 0, .arg3 = 0, .arg4 = 0 },
//         [3] = { .OPCODE = OP_ADD_VEL, .arg1 = 50, .arg2 = 0, .arg3 = 0, .arg4 = 0 },
//         [4] = { .OPCODE = OP_DESPAWN, .arg1 = 0, .arg2 = 0, .arg3 = 0, .arg4 = 0 }
//     }
// )

// BULLET_SCRIPT(
// 	.ID = "boss_spiral",
//     .Count = 3,
//     .Instr = {
//         [0] = { .OPCODE = OP_SPAWN, .arg1 = 5, .arg2 = 0, .arg3 = 0, .arg4 = 0 },
//         [1] = { .OPCODE = OP_SET_DIR, .arg1 = 0, .arg2 = 360, .arg3 = 2, .arg4 = 0 },
//         [2] = { .OPCODE = OP_DESPAWN, .arg1 = 0, .arg2 = 0, .arg3 = 0, .arg4 = 0 }
//     }
// )